#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# mwc.pl -type make
#
#----------------------------------------------------------------------------


all: pipeandfilter

depend: pipeandfilter-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.pipeandfilter $(@)

.PHONY: pipeandfilter
pipeandfilter:
	@$(MAKE) -f Makefile.pipeandfilter all

.PHONY: pipeandfilter-depend
pipeandfilter-depend:
	@$(MAKE) -f Makefile.pipeandfilter depend

project_name_list:
	@echo pipeandfilter
